# mode: ContinuousDeployment
# # next-version: 1.0.0
# branches:
#   master:
#     regex: ^master$
#     tag: alpha
#     increment: Patch
#   release:
#     regex: ^release[/-]
#     tag: beta
#     increment: Minor

# mode: Mainline
# branches:
#   master:
#     tag: ''
#     increment: Patch

# mode: ContinuousDeployment
# # next-version: 1.0.0
# branches:
#   master:
#     regex: ^master$
#     tag: alpha
#     increment: Patch
#   release:
#     regex: ^release[/-]
#     tag: beta
#     increment: Minor

# mode: Mainline
# branches:
#   master:
#     tag: ''
#     increment: Patch

mode: Mainline
increment: Inherit
update-build-number: true
branches:
  main:
    regex: ^main$
    is-mainline: true
  feature:
    regex: ^features?[/-]
    tag: useBranchName
    increment: Minor
  hotfix:
    regex: ^(bugfix|hotfix(es)?)[/-]
    tag: useBranchName
    increment: Patch
