assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDeployment
branches:
  develop:
    tag: ''
  feature:
    tag: ''
  release:
    tag: test
    increment: Patch
    tracks-release-branches: true
    source-branches:
      - develop
      - bugfix
  bugfix:
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    regex: bugfix(es)?[/-]
    source-branches:
      - release
ignore:
  sha: []
