mode: Mainline
increment: Inherit
update-build-number: true
branches:
  master:
    regex: ^master$
    is-mainline: true
  feature:
    regex: ^features?[/-]
    tag: useBranchName
    increment: Minor
  hotfix:
    regex: ^(bugfix|hotfix(es)?)[/-]
    tag: useBranchName
    increment: Patch
