name: Build and Version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.x # Adjust to your project's requirements

      - name: Restore Dependencies
        run: dotnet restore

      - name: Run GitVersion
        run: |
          # Install GitVersion tool
          dotnet tool install --global GitVersion.Tool --version "5.x.x" # Adjust to the desired version

          # Run GitVersion
          gitversion
        id: gitversion

      - name: Display Version
        run: echo "Generated Version ${{ steps.gitversion.outputs.FullSemVer }}"

    # Add more steps for building, testing, and deploying your code as needed.
